# Python Lists vs. Numpy Arrays - What is the difference?



### Size - Numpy data structures take up less space
### Performance - they have a need for speed and are faster than lists
### Functionality - SciPy and NumPy have optimized functions such as linear algebra operations built in
###### https://www.tutorialspoint.com/numpy/numpy_ndarray_flat.htm

In [26]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np
a = np.array([1,2,3]) 
print(a)

[1 2 3]


In [5]:
a = np.array([1, 2, 3], dtype = float) # we specify that the numbers are float
print(a)

[1. 2. 3.]


In [8]:
print(a.shape)

(3,)


In [9]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [10]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c.shape)

(2, 2, 3)


# Creating arrays 

In [12]:
d = np.arange(24)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [13]:
e = d.reshape(3,8)
print(e)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [15]:
x = np.zeros((5,), dtype = int) 
print(x)

[0 0 0 0 0]


In [16]:
x = np.zeros((2,2))
print(x)

[[0. 0.]
 [0. 0.]]


In [18]:
y = np.ones(5, dtype = int) 
print(y)

[1 1 1 1 1]


In [25]:
q = np.linspace(10,20,5)
print(q)

[10.  12.5 15.  17.5 20. ]


In [24]:
x = [1,2,3]

y = np.asarray(x)

print(y)

print(type(y))
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>
<class 'list'>


# slicing the data

In [27]:
a = np.arange(10)
print(a)

b = a[2:7:2] 
print(b)

b = a[5]
print(b)

print(a[2:])

print(a[2:5])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
5
[2 3 4 5 6 7 8 9]
[2 3 4]


In [31]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)
print('\n')

print(a[1:])
print('\n')

print(a[...,1])
print('\n')

print(a[1,...])

[[1 2 3]
 [3 4 5]
 [4 5 6]]


[[3 4 5]
 [4 5 6]]


[2 4 5]


[3 4 5]


# looping through an array

In [37]:
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
print(a)
print('\n')

for x in a:
    print(x)

print('\n')
for x in np.nditer(a, order = 'F'):
    print(x)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


[ 0  5 10 15]
[20 25 30 35]
[40 45 50 55]


0
20
40
5
25
45
10
30
50
15
35
55
